version: "3.9"

services:
  db:
    image: postgres:15
    container_name: estore-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: estore
    volumes:
      - db-data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: estore-backend
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASS: postgres
      DB_NAME: estore
      DB_DIALECT: postgres
      JWT_SECRET: mysecretjwtkey
      FRONTEND_ORIGIN: http://localhost:3000
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: estore-frontend
    ports:
      - "3000:80"
    depends_on:
      - backend

volumes:
  db-data: